name: logintunisia
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  card_swiper: ^3.0.1
  image_picker: ^1.0.1
  # tflite: any
  http: ^1.1.0
  geolocator : ^9.0.2
  image: ^4.0.17
  path_provider: ^2.0.5
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.4
  firebase_core: "2.15.0"
  firebase_auth: "4.7.2"
  cloud_firestore: "4.8.4"
  firebase_storage: "11.2.5"
  uuid: ^3.0.4
  tflite_flutter: ^0.10.1
  camera: ^0.10.5+2
  
  #theme stuff
  flutter_svg: "2.0.7"
  google_fonts: "5.1.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "0.13.0"

flutter_icons:
  ios: true
  image_path: "assets/icons/icon.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/weather_icon.png
    - assets/images/placeholder_image.png 
    - assets/models/
    - assets/images/maha.jpeg
    - assets/images/rain.jpeg
    - assets/images/agri.jpeg
    - assets/icons/farmersConnect_icon.png
