// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNScBc7CS_VQ600mQn0FyRRaLsHz9voSw',
    appId: '1:431421130883:web:5d9afe307cbba4f4c1b3b6',
    messagingSenderId: '431421130883',
    projectId: 'farmersconnect-21f53',
    authDomain: 'farmersconnect-21f53.firebaseapp.com',
    storageBucket: 'farmersconnect-21f53.appspot.com',
    measurementId: 'G-3G13XCBJPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8AusuvxY4rL61kAyjmIqbWLDpKu7l1Pg',
    appId: '1:431421130883:android:03c20031335144d5c1b3b6',
    messagingSenderId: '431421130883',
    projectId: 'farmersconnect-21f53',
    storageBucket: 'farmersconnect-21f53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm4XLfrdkvMH8eZ5NUFn86HiuaA9sW3Zk',
    appId: '1:431421130883:ios:59a46407f49203adc1b3b6',
    messagingSenderId: '431421130883',
    projectId: 'farmersconnect-21f53',
    storageBucket: 'farmersconnect-21f53.appspot.com',
    androidClientId: '431421130883-gh58ik7048190ukd7vkbhgfslnegkbgu.apps.googleusercontent.com',
    iosClientId: '431421130883-m3g57i2drfif24qi5jg4sob10uo8vk02.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmersConnect',
  );
}
